AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'lambda layer for connection to pymysql

  '
Resources:
  LambdaLayerPymysql:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: LambdaLayerPymysql
      Description: Provides db connection functionality
      ContentUri: s3://1s-lambda-layer-pymysql/bff2334da72ff39e48edfb59738b642c
      CompatibleRuntimes:
      - python3.7
      RetentionPolicy: Retain
Outputs:
  LambdaLayerPymysql:
    Description: Arn for pymysql lambda layer
    Value:
      Ref: LambdaLayerPymysql
